apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch3-pv
  labels:
    pv: elasticsearch3-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-node03
    path: "/media/elasticsearch3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch3-pvc
spec:
  selector:
    matchLabels:
      pv: elasticsearch3-pv
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch3
  labels:
    name: elasticsearch3
spec:
  ports:
    - name: http1
      port: 9200
      targetPort: 9200
      nodePort: 32032
    - name: http2
      port: 9300
      targetPort: 9300
      nodePort: 32033
  selector:
    name: elasticsearch3
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch3
    spec:
      hostname: elasticsearch3
      containers:
        - name: elasticsearch3
          image: registry.cn-hangzhou.aliyuncs.com/lvxw_test/k8s-elasticsearch-6.1.0:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
              name: http1
            - containerPort: 9230
              name: http2
          env:
          - name: NODE_NAME
            value: elasticsearch3
          volumeMounts:
            - name: elasticsearch3-persistent-storage
              mountPath: /data/elasticsearch/data
      volumes:
        - name: elasticsearch3-persistent-storage
          persistentVolumeClaim:
            claimName: elasticsearch3-pvc