apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch2-pv
  labels:
    pv: elasticsearch2-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-node02
    path: "/media/elasticsearch2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch2-pvc
spec:
  selector:
    matchLabels:
      pv: elasticsearch2-pv
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch2
  labels:
    name: elasticsearch2
spec:
  ports:
    - name: http1
      port: 9200
      targetPort: 9200
      nodePort: 32022
  selector:
    name: elasticsearch2
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch2
    spec:
      hostname: elasticsearch2
      containers:
        - name: elasticsearch2
          image: registry.cn-hangzhou.aliyuncs.com/lvxw_test/k8s-elasticsearch-6.1.0:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
              name: http1
            - containerPort: 9300
              name: http2
          volumeMounts:
            - name: elasticsearch2-persistent-storage
              mountPath: /data/elasticsearch/data
      volumes:
        - name: elasticsearch2-persistent-storage
          persistentVolumeClaim:
            claimName: elasticsearch2-pvc