apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    name: master
spec:
    ports:
    - name: rpc1
      port: 16000
    - name: rpc2
      port: 16010
  selector:
    name: master
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: master
    spec:
      hostname: master
      containers:
        - name: master
          image: registry.cn-hangzhou.aliyuncs.com/lvxw_test/k8s-hbase-1.4.12:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16000
              protocol: TCP
              name: rpc1
            - containerPort: 16010
              protocol: TCP
              name: rpc2
          env:
          - name: PROC_TYPE
            value: master