apiVersion: v1
kind: Service
metadata:
  name: regionserver1
  labels:
    name: regionserver1
spec:
  ports:
    - name: rpc1
      port: 16020
    - name: rpc2
      port: 16030
  selector:
    name: regionserver1
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: regionserver1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: regionserver1
    spec:
      hostname: regionserver1
      containers:
        - name: regionserver1
          image: registry.cn-hangzhou.aliyuncs.com/lvxw_test/k8s-hbase-1.4.12:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16020
              protocol: TCP
              name: rpc1
            - containerPort: 16030
              protocol: TCP
              name: rpc2
          env:
          - name: PROC_TYPE
            value: regionserver