apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper3-pv
  labels:
    pv: zookeeper3-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-node03
    path: "/media/zookeeper3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper3-pvc
spec:
  selector:
    matchLabels:
      pv: zookeeper3-pv
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper3-svc
  labels:
    name: zookeeper3
spec:
  type: NodePort
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    name: zookeeper3
    nodePort: 32186
  selector:
    app: zookeeper3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper3
  template:
    metadata:
      labels:
        app: zookeeper3
    spec:
      hostname: zookeeper3
      containers:
      - name: zookeeper3
        image: registry.cn-hangzhou.aliyuncs.com/lvxw_test/k8s-zookeeper-3.4.14:v1
        env:
        - name: NODE_NUMBER
          value: "3"
        ports:
        - containerPort: 2181
          name: zookeeper3
        volumeMounts:
        - name: zookeeper3-persistent-storage
          mountPath: /data/zookeeper/data
      volumes:
      - name: zookeeper3-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper3-pvc
